- hosts: webservers
  become: true
  gather_facts: true
  tasks:
    - name: Copy Flask app to remote server
      copy:
        src: ./application2.py
        dest: /home/ubuntu/application2.py
        mode: '0755'

    - name: Install Python 3 and pip
      become: true
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Install Flask
      become: true
      pip:
        name: Flask

    - name: Create systemd unit file for application2
      copy:
        src: ./application2.service
        dest: /etc/systemd/system/application2.service
        mode: '0777'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start application2 service
      systemd:
        name: application2.service
        state: started
        enabled: yes

    - name: apt update
      apt:
        update_cache: true

- hosts: HAproxy
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: latest
        
    - name: Install HAProxy
      apt:
        name: haproxy
        state: latest

    - name: Configure HAProxy
      template:
        src: ./haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      vars:
        haproxy_ip: "{{ hostvars['HAproxy']['ansible_default_ipv4']['address'] }}"
      when: "'ansible_default_ipv4' in hostvars['HAproxy']"
                
    - name: Restart haproxy
      ansible.builtin.shell:
        cmd: "sudo service haproxy restart"
